add checksum check

diff --git a/.github/workflows/metadata_schema_check.yml b/.github/workflows/metadata_schema_check.yml
--- a/.github/workflows/metadata_schema_check.yml
+++ b/.github/workflows/metadata_schema_check.yml
@@ -22,6 +22,7 @@ jobs:
 
   fetch-modified-metadata:
     name: Fetch modified metadata
+    needs: [validate-json-schema]
     runs-on: ubuntu-latest
     permissions:
       pull-requests: read
@@ -85,6 +86,9 @@ jobs:
           echo "source_builder_tag=$SOURCE_BUILDER_TAG" >> $GITHUB_OUTPUT
           echo "source_builder_contract_name=$SOURCE_BUILDER_CONTRACT_NAME" >> $GITHUB_OUTPUT
 
+          CODE_ID=$(cat ${{ matrix.file }} | jq -r '.code_id')
+          echo "code_id=$CODE_ID" >> $GITHUB_OUTPUT
+
       
       - name: Checkout source code
         id: checkoutcode
@@ -96,12 +100,34 @@ jobs:
       - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Build the binary
+      - name: Build the binary and get checksum
         run: |
           docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry   ${{ steps.setmetadata.outputs.source_builder_image }}:${{ steps.setmetadata.outputs.source_builder_tag }}
-
-      - name: Fetch the contract checksum
-        run: |
-          CHECKSUMLINE=$(grep -n ${{ steps.setmetadata.outputs.source_builder_contract_name }} artifacts/checksums.txt )
+          CHECKSUMLINE=$(grep -h ${{ steps.setmetadata.outputs.source_builder_contract_name }} artifacts/checksums.txt )
           CHECKSUM=$(echo $CHECKSUMLINE | cut -d ' ' -f 1)
-          echo $CHECKSUM
+          echo "source_contract_checksum=$CHECKSUM" >> $GITHUB_OUTPUT
+
+      - name: Verify checksums
+        run: |
+          NETWORK=$(echo "$string" | cut -d '/' -f 1)
+          REST_URL=""
+          if [[ "$NETWORK" == "mainnet" ]]; then
+            REST_URL=https://api.mainnet.archway.io/cosmwasm/wasm/v1/code/${{ steps.setmetadata.outputs.code_id }}
+          elif [[ "$NETWORK" == "testnet" ]]; then
+            REST_URL=https://api.constantine.archway.tech/cosmwasm/wasm/v1/code/${{ steps.setmetadata.outputs.code_id }}
+          else
+            echo "Invalid network path found"
+          fi
+
+          HASH=$(curl -X GET $REST_URL -H  "accept: application/json" | jq -r '.code_info.data_hash' | tr '[:upper:]' '[:lower:]')
+          GENERATED_HASH=${{ steps.setmetadata.outputs.source_contract_checksum }}
+
+          echo "hash=$HASH" 
+          echo "generated=$GENERATED_HASH" 
+
+          if [[ "$HASH" == "$GENERATED_HASH" ]]; then
+            echo "The strings are the same"
+          else
+            echo "The hashes do not match"
+            exit 1
+          fi
